# Storage for all packages
storage: /verdaccio/storage

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  #enable: false
  title: npm
  logo: https://i.imgur.com/2wCZ7xe.png

auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
    
listen:
  - 0.0.0.0:4873

logs:
  - {type: stdout, format: pretty, level: info}


# A list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    timeout: 10s
    maxage: 10m
    
packages:
  '@*/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated

  '*':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $authenticated

    # Allow authenticated users to publish packages
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs
